[colors.primary]
background = "#000000"
foreground = "#f06800"

[colors.normal]
black = "#505050"
blue = "#5090c8"
cyan = "#60f0a0"
green = "#409820"
magenta = "#7058a4"
red = "#c00010"
white = "#a0a0a0"
yellow = "#f0f0a0"

[colors.bright]
black = "#707070"
blue = "#40c8e8"
cyan = "#3cffd0"
green = "#50ff10"
magenta = "#b040a0"
red = "#e00010"
white = "#f8f8f8"
yellow = "#f4b000"

[colors.selection]
background = "#c00010"