[colors.primary]
background = "#000000"
foreground = "#f06800"

[colors.normal]
black = "#000000"
red = "#a00010"
green = "#409820"
yellow = "#f0f0a0"
blue = "#5090c8"
magenta = "#7058a4"
cyan = "#60f0a0"
white = "#b0b0b0"

[colors.bright]
black = "#484848"
red = "#c80010"
green = "#50ff10"
yellow = "#f4b000"
blue = "#40c8e8"
magenta = "#b040a0"
cyan = "#3cffd0"
white = "#f8f8f8"

[colors.selection]
background = "#c80010"
foreground = "#000000"

[colors.footer_bar]
background = "#f4b000"
foreground = "#000000"

[colors.search.matches]
background = "#f0f0a0"
foreground = "#000000"

[colors.search.focused_match]
background = "#f4b000"
foreground = "#000000"

[[colors.indexed_colors]]
index = 202
color = "#f06800"