# name: magi-16

fish_color_normal normal
fish_color_command bryellow
fish_color_keyword brgreen
fish_color_quote green
fish_color_redirection brgreen --bold
fish_color_end magenta
fish_color_error brred
fish_color_param cyan
fish_color_valid_path --underline
fish_color_option brcyan
fish_color_comment white
fish_color_selection black --background=brred --bold
fish_color_operator brmagenta --bold
fish_color_escape yellow
fish_color_autosuggestion brblack
fish_color_cwd brblue
fish_color_user yellow
fish_color_host blue
fish_color_host_remote green
fish_color_status red
fish_color_cancel --reverse
fish_color_search_match bryellow --background=brblack --bold
fish_color_history_current --bold

fish_pager_color_progress black --background=yellow --bold
fish_pager_color_prefix normal --bold --underline
fish_pager_color_completion normal
fish_pager_color_description yellow --italics
fish_pager_color_selected_background --reverse
