# name: magi-16

fish_color_normal normal
fish_color_command bryellow
fish_color_quote yellow
fish_color_redirection cyan --bold
fish_color_end brmagenta
fish_color_error brred
fish_color_param cyan
fish_color_comment white
fish_color_match --background=brblue
fish_color_search_match bryellow --background=brblack
fish_color_selection black --bold --background=brred
fish_color_history_current --bold
fish_color_operator brgreen
fish_color_escape magenta
fish_color_cwd brblue
fish_color_valid_path --underline
fish_color_cwd_root red
fish_color_user yellow
fish_color_autosuggestion brblack
fish_pager_color_completion normal
fish_color_host blue
fish_pager_color_description yellow -i
fish_color_cancel -r
fish_pager_color_prefix normal --bold --underline
fish_pager_color_progress black --background=yellow
fish_pager_color_selected_background -r
fish_color_option brcyan
fish_color_keyword normal
fish_color_host_remote green
fish_color_status red
